<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/company.proto

namespace GPBMetadata\Common;

class Company
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aea010a14636f6d6d6f6e2f636f6d70616e792e70726f746f1206636f6d" .
            "6d6f6e22a4010a07436f6d70616e7912130a0b646973706c61794e616d65" .
            "180120012809120f0a076f776e6572496418022001280912110a09637265" .
            "617465644174180320012803122f0a086d65746164617461180e2003280b" .
            "321d2e636f6d6d6f6e2e436f6d70616e792e4d65746164617461456e7472" .
            "791a2f0a0d4d65746164617461456e747279120b0a036b65791801200128" .
            "09120d0a0576616c75651802200128093a023801421bca0218416c666174" .
            "7261696e696e675c477270635c436f6d6d6f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

