<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication/authenticationService.proto

namespace Alfatraining\Grpc\Authentication;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * AuthenticationReply contains information about the response.
 *
 * Generated from protobuf message <code>authentication.AuthenticationReply</code>
 */
class AuthenticationReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     */
    private $replyInfo = null;
    /**
     * Generated from protobuf field <code>bytes accessToken = 6;</code>
     */
    private $accessToken = '';
    /**
     * timestamp of token expiration
     *
     * Generated from protobuf field <code>int64 expiresAt = 7;</code>
     */
    private $expiresAt = 0;
    /**
     * exchange for a new access token by using the refresh token grant
     *
     * Generated from protobuf field <code>string refreshToken = 8;</code>
     */
    private $refreshToken = '';
    /**
     * Generated from protobuf field <code>string userId = 11;</code>
     */
    private $userId = '';
    /**
     * permissions of the access token (map to names using the common.BackendPermission enum keys)
     *
     * Generated from protobuf field <code>map<int32, bool> permissions = 12;</code>
     */
    private $permissions;
    /**
     * Generated from protobuf field <code>.authentication.AccountStatus accountStatus = 13;</code>
     */
    private $accountStatus = 0;

    public function __construct() {
        \GPBMetadata\Authentication\AuthenticationService::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     * @return \Alfatraining\Grpc\Common\ReplyInfo
     */
    public function getReplyInfo()
    {
        return $this->replyInfo;
    }

    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     * @param \Alfatraining\Grpc\Common\ReplyInfo $var
     * @return $this
     */
    public function setReplyInfo($var)
    {
        GPBUtil::checkMessage($var, \Alfatraining\Grpc\Common\ReplyInfo::class);
        $this->replyInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes accessToken = 6;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->accessToken;
    }

    /**
     * Generated from protobuf field <code>bytes accessToken = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->accessToken = $var;

        return $this;
    }

    /**
     * timestamp of token expiration
     *
     * Generated from protobuf field <code>int64 expiresAt = 7;</code>
     * @return int|string
     */
    public function getExpiresAt()
    {
        return $this->expiresAt;
    }

    /**
     * timestamp of token expiration
     *
     * Generated from protobuf field <code>int64 expiresAt = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->expiresAt = $var;

        return $this;
    }

    /**
     * exchange for a new access token by using the refresh token grant
     *
     * Generated from protobuf field <code>string refreshToken = 8;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->refreshToken;
    }

    /**
     * exchange for a new access token by using the refresh token grant
     *
     * Generated from protobuf field <code>string refreshToken = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->refreshToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userId = 11;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>string userId = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * permissions of the access token (map to names using the common.BackendPermission enum keys)
     *
     * Generated from protobuf field <code>map<int32, bool> permissions = 12;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * permissions of the access token (map to names using the common.BackendPermission enum keys)
     *
     * Generated from protobuf field <code>map<int32, bool> permissions = 12;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->permissions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authentication.AccountStatus accountStatus = 13;</code>
     * @return int
     */
    public function getAccountStatus()
    {
        return $this->accountStatus;
    }

    /**
     * Generated from protobuf field <code>.authentication.AccountStatus accountStatus = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountStatus($var)
    {
        GPBUtil::checkEnum($var, \Alfatraining\Grpc\Authentication\AccountStatus::class);
        $this->accountStatus = $var;

        return $this;
    }

}

