<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication/authenticationService.proto

namespace Alfatraining\Grpc\Authentication;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * CompanySwitchCredentials are used to switch to another company the user
 * is also a part of. All fields are required.
 * Use the ListAuthentications endpoint to list all the companies you're a part of.
 *
 * Generated from protobuf message <code>authentication.CompanySwitchCredentials</code>
 */
class CompanySwitchCredentials extends \Google\Protobuf\Internal\Message
{
    /**
     * a valid access token
     *
     * Generated from protobuf field <code>bytes accessToken = 1;</code>
     */
    private $accessToken = '';
    /**
     * a valid refresh token for the access token above
     *
     * Generated from protobuf field <code>string refreshToken = 2;</code>
     */
    private $refreshToken = '';
    /**
     * the company to switch to
     *
     * Generated from protobuf field <code>string companyId = 3;</code>
     */
    private $companyId = '';
    /**
     * identifier used to create the access/refresh token
     *
     * Generated from protobuf field <code>string principal = 4;</code>
     */
    private $principal = '';

    public function __construct() {
        \GPBMetadata\Authentication\AuthenticationService::initOnce();
        parent::__construct();
    }

    /**
     * a valid access token
     *
     * Generated from protobuf field <code>bytes accessToken = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->accessToken;
    }

    /**
     * a valid access token
     *
     * Generated from protobuf field <code>bytes accessToken = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->accessToken = $var;

        return $this;
    }

    /**
     * a valid refresh token for the access token above
     *
     * Generated from protobuf field <code>string refreshToken = 2;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->refreshToken;
    }

    /**
     * a valid refresh token for the access token above
     *
     * Generated from protobuf field <code>string refreshToken = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->refreshToken = $var;

        return $this;
    }

    /**
     * the company to switch to
     *
     * Generated from protobuf field <code>string companyId = 3;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->companyId;
    }

    /**
     * the company to switch to
     *
     * Generated from protobuf field <code>string companyId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->companyId = $var;

        return $this;
    }

    /**
     * identifier used to create the access/refresh token
     *
     * Generated from protobuf field <code>string principal = 4;</code>
     * @return string
     */
    public function getPrincipal()
    {
        return $this->principal;
    }

    /**
     * identifier used to create the access/refresh token
     *
     * Generated from protobuf field <code>string principal = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipal($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal = $var;

        return $this;
    }

}

