<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/company.proto

namespace Alfatraining\Grpc\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.Company</code>
 */
class Company extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; display name of a company (e.g. used inside the company dropdown)
     *
     * Generated from protobuf field <code>string displayName = 1;</code>
     */
    private $displayName = '';
    /**
     *&#47; email of the user that created the company
     *
     * Generated from protobuf field <code>string ownerId = 2;</code>
     */
    private $ownerId = '';
    /**
     *&#47; date of creation
     *
     * Generated from protobuf field <code>int64 createdAt = 3;</code>
     */
    private $createdAt = 0;
    /**
     *&#47; branding
     *
     * Generated from protobuf field <code>.common.Branding branding = 4;</code>
     */
    private $branding = null;
    /**
     * Generated from protobuf field <code>map<string, string> metadata = 14;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $displayName
     *          &#47; display name of a company (e.g. used inside the company dropdown)
     *     @type string $ownerId
     *          &#47; email of the user that created the company
     *     @type int|string $createdAt
     *          &#47; date of creation
     *     @type \Alfatraining\Grpc\Common\Branding $branding
     *          &#47; branding
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Company::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; display name of a company (e.g. used inside the company dropdown)
     *
     * Generated from protobuf field <code>string displayName = 1;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     *&#47; display name of a company (e.g. used inside the company dropdown)
     *
     * Generated from protobuf field <code>string displayName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->displayName = $var;

        return $this;
    }

    /**
     *&#47; email of the user that created the company
     *
     * Generated from protobuf field <code>string ownerId = 2;</code>
     * @return string
     */
    public function getOwnerId()
    {
        return $this->ownerId;
    }

    /**
     *&#47; email of the user that created the company
     *
     * Generated from protobuf field <code>string ownerId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ownerId = $var;

        return $this;
    }

    /**
     *&#47; date of creation
     *
     * Generated from protobuf field <code>int64 createdAt = 3;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     *&#47; date of creation
     *
     * Generated from protobuf field <code>int64 createdAt = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->createdAt = $var;

        return $this;
    }

    /**
     *&#47; branding
     *
     * Generated from protobuf field <code>.common.Branding branding = 4;</code>
     * @return \Alfatraining\Grpc\Common\Branding
     */
    public function getBranding()
    {
        return $this->branding;
    }

    /**
     *&#47; branding
     *
     * Generated from protobuf field <code>.common.Branding branding = 4;</code>
     * @param \Alfatraining\Grpc\Common\Branding $var
     * @return $this
     */
    public function setBranding($var)
    {
        GPBUtil::checkMessage($var, \Alfatraining\Grpc\Common\Branding::class);
        $this->branding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 14;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 14;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

}

