<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/permissions.proto

namespace Alfatraining\Grpc\Common;

/**
 * Protobuf type <code>common.RoomPermission</code>
 */
class RoomPermission
{
    /**
     * Generated from protobuf enum <code>_ = 0;</code>
     */
    const _ = 0;
    /**
     * Generated from protobuf enum <code>ADMIN = 1;</code>
     */
    const ADMIN = 1;
    /**
     * Generated from protobuf enum <code>VOICE = 2;</code>
     */
    const VOICE = 2;
    /**
     * Generated from protobuf enum <code>VIDEO = 3;</code>
     */
    const VIDEO = 3;
    /**
     * Generated from protobuf enum <code>PROMOTE = 4;</code>
     */
    const PROMOTE = 4;
    /**
     * Generated from protobuf enum <code>JOIN = 5;</code>
     */
    const JOIN = 5;
    /**
     * Generated from protobuf enum <code>SCREEN = 6;</code>
     */
    const SCREEN = 6;
    /**
     * Generated from protobuf enum <code>VIP = 7;</code>
     */
    const VIP = 7;
    /**
     * Generated from protobuf enum <code>SUBROOM_MANAGE = 8;</code>
     */
    const SUBROOM_MANAGE = 8;
    /**
     * Generated from protobuf enum <code>SUBROOM_CREATE_PUBLIC = 9;</code>
     */
    const SUBROOM_CREATE_PUBLIC = 9;
    /**
     * Generated from protobuf enum <code>SUBROOM_CREATE_PRIVATE = 15;</code>
     */
    const SUBROOM_CREATE_PRIVATE = 15;
    /**
     * Generated from protobuf enum <code>CHAT = 10;</code>
     */
    const CHAT = 10;
    /**
     * Generated from protobuf enum <code>CHAT_BROADCAST = 11;</code>
     */
    const CHAT_BROADCAST = 11;
    /**
     * Generated from protobuf enum <code>FILE_ADMIN = 20;</code>
     */
    const FILE_ADMIN = 20;
    /**
     * Generated from protobuf enum <code>FILE_UPLOAD = 21;</code>
     */
    const FILE_UPLOAD = 21;
    /**
     * Generated from protobuf enum <code>FILE_LIST = 22;</code>
     */
    const FILE_LIST = 22;
    /**
     * Generated from protobuf enum <code>FAIR_USE = 25;</code>
     */
    const FAIR_USE = 25;
    /**
     * Generated from protobuf enum <code>ACTION = 30;</code>
     */
    const ACTION = 30;
}

