<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/room.proto

namespace Alfatraining\Grpc\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.SubRoom</code>
 */
class SubRoom extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string displayName = 3;</code>
     */
    private $displayName = '';
    /**
     * custom sorting key to determine the order of subrooms in the UI
     *
     * Generated from protobuf field <code>uint32 sort = 4;</code>
     */
    private $sort = 0;
    /**
     * workaround for python's inability to handle maps with null-values
     *
     * Generated from protobuf field <code>bool remove = 5;</code>
     */
    private $remove = false;

    public function __construct() {
        \GPBMetadata\Common\Room::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string displayName = 3;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * Generated from protobuf field <code>string displayName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->displayName = $var;

        return $this;
    }

    /**
     * custom sorting key to determine the order of subrooms in the UI
     *
     * Generated from protobuf field <code>uint32 sort = 4;</code>
     * @return int
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * custom sorting key to determine the order of subrooms in the UI
     *
     * Generated from protobuf field <code>uint32 sort = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkUint32($var);
        $this->sort = $var;

        return $this;
    }

    /**
     * workaround for python's inability to handle maps with null-values
     *
     * Generated from protobuf field <code>bool remove = 5;</code>
     * @return bool
     */
    public function getRemove()
    {
        return $this->remove;
    }

    /**
     * workaround for python's inability to handle maps with null-values
     *
     * Generated from protobuf field <code>bool remove = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setRemove($var)
    {
        GPBUtil::checkBool($var);
        $this->remove = $var;

        return $this;
    }

}

