<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/user.proto

namespace Alfatraining\Grpc\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string email = 1;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>map<string, string> metadata = 14;</code>
     */
    private $metadata;
    /**
     * Generated from protobuf field <code>.common.UserProfile userProfile = 15;</code>
     */
    private $userProfile = null;

    public function __construct() {
        \GPBMetadata\Common\User::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 14;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 14;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.common.UserProfile userProfile = 15;</code>
     * @return \Alfatraining\Grpc\Common\UserProfile
     */
    public function getUserProfile()
    {
        return $this->userProfile;
    }

    /**
     * Generated from protobuf field <code>.common.UserProfile userProfile = 15;</code>
     * @param \Alfatraining\Grpc\Common\UserProfile $var
     * @return $this
     */
    public function setUserProfile($var)
    {
        GPBUtil::checkMessage($var, \Alfatraining\Grpc\Common\UserProfile::class);
        $this->userProfile = $var;

        return $this;
    }

}

