<?php
/**
 * GuestServiceV2State
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * guestServiceV2/guestService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Alfaview\Model;
use \Alfaview\ObjectSerializer;

/**
 * GuestServiceV2State Class Doc Comment
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GuestServiceV2State
{
    /**
     * Possible values of this enum
     */
    const UNDEFINED = 'UNDEFINED';
    const QUEUED = 'QUEUED';
    const ASSIGNED = 'ASSIGNED';
    const FAILED = 'FAILED';
    const FAILED_PERMANENTLY = 'FAILED_PERMANENTLY';
    const DONE = 'DONE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNDEFINED,
            self::QUEUED,
            self::ASSIGNED,
            self::FAILED,
            self::FAILED_PERMANENTLY,
            self::DONE,
        ];
    }
}


