<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/userService.proto

namespace Alfatraining\Grpc\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.UserListRequest</code>
 */
class UserListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.AccessInfo accessInfo = 1;</code>
     */
    private $accessInfo = null;
    /**
     * list of user IDs that you want to query for
     *
     * Generated from protobuf field <code>repeated string userIdList = 9;</code>
     */
    private $userIdList;

    public function __construct() {
        \GPBMetadata\User\UserService::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.common.AccessInfo accessInfo = 1;</code>
     * @return \Alfatraining\Grpc\Common\AccessInfo
     */
    public function getAccessInfo()
    {
        return $this->accessInfo;
    }

    /**
     * Generated from protobuf field <code>.common.AccessInfo accessInfo = 1;</code>
     * @param \Alfatraining\Grpc\Common\AccessInfo $var
     * @return $this
     */
    public function setAccessInfo($var)
    {
        GPBUtil::checkMessage($var, \Alfatraining\Grpc\Common\AccessInfo::class);
        $this->accessInfo = $var;

        return $this;
    }

    /**
     * list of user IDs that you want to query for
     *
     * Generated from protobuf field <code>repeated string userIdList = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserIdList()
    {
        return $this->userIdList;
    }

    /**
     * list of user IDs that you want to query for
     *
     * Generated from protobuf field <code>repeated string userIdList = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->userIdList = $arr;

        return $this;
    }

}

