<?php
/**
 * MeetingCreate
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Alfaview\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * alfaview
 *
 * ## Format information * All time fields are returned in RFC3339 format and in UTC if not mentioned otherwise.  ## Authentication ### API Key and Credentials All API requests require an access token for authorization. Access tokens can be obtained by authenticating using any of the following endpoints: - [Authenticate via API key](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticateAPIKey) - [Authenticate via password](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticatePassword) - [Authenticate a guest (guest link)](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticateGuestLink) - [Authenticate a guest (group link)](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticateGroupLink) The access token is returned as a base64-encoded string. It needs to be used as the value in the `Authorization` header in all subsequent API requests.  ### Token Time-To-Live (TTL) Access tokens are valid for 1 hour. After this period, tokens will be expired and a new token must be obtained.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alfaview\Client\Model;

use \ArrayAccess;
use \Alfaview\Client\ObjectSerializer;

/**
 * MeetingCreate Class Doc Comment
 *
 * @category Class
 * @package  Alfaview\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MeetingCreate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MeetingCreate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'agenda' => 'string',
        'early_access_minutes' => 'int',
        'end' => '\DateTime',
        'group_links' => '\Alfaview\Client\Model\GroupLinkCreate[]',
        'guest_links' => '\Alfaview\Client\Model\GuestLinkCreate[]',
        'room_features' => '\Alfaview\Client\Model\RoomFeatures',
        'start' => '\DateTime',
        'subroom_display_names' => 'string[]',
        'timezone' => 'string',
        'title' => 'string',
        'waiting_room_enabled' => 'bool',
        'waiting_room_welcome_note' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'agenda' => null,
        'early_access_minutes' => 'int64',
        'end' => 'date-time',
        'group_links' => null,
        'guest_links' => null,
        'room_features' => null,
        'start' => 'date-time',
        'subroom_display_names' => null,
        'timezone' => null,
        'title' => null,
        'waiting_room_enabled' => null,
        'waiting_room_welcome_note' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'agenda' => true,
        'early_access_minutes' => true,
        'end' => false,
        'group_links' => true,
        'guest_links' => true,
        'room_features' => false,
        'start' => false,
        'subroom_display_names' => true,
        'timezone' => false,
        'title' => false,
        'waiting_room_enabled' => false,
        'waiting_room_welcome_note' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'agenda' => 'agenda',
        'early_access_minutes' => 'earlyAccessMinutes',
        'end' => 'end',
        'group_links' => 'groupLinks',
        'guest_links' => 'guestLinks',
        'room_features' => 'roomFeatures',
        'start' => 'start',
        'subroom_display_names' => 'subroomDisplayNames',
        'timezone' => 'timezone',
        'title' => 'title',
        'waiting_room_enabled' => 'waitingRoomEnabled',
        'waiting_room_welcome_note' => 'waitingRoomWelcomeNote'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'agenda' => 'setAgenda',
        'early_access_minutes' => 'setEarlyAccessMinutes',
        'end' => 'setEnd',
        'group_links' => 'setGroupLinks',
        'guest_links' => 'setGuestLinks',
        'room_features' => 'setRoomFeatures',
        'start' => 'setStart',
        'subroom_display_names' => 'setSubroomDisplayNames',
        'timezone' => 'setTimezone',
        'title' => 'setTitle',
        'waiting_room_enabled' => 'setWaitingRoomEnabled',
        'waiting_room_welcome_note' => 'setWaitingRoomWelcomeNote'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'agenda' => 'getAgenda',
        'early_access_minutes' => 'getEarlyAccessMinutes',
        'end' => 'getEnd',
        'group_links' => 'getGroupLinks',
        'guest_links' => 'getGuestLinks',
        'room_features' => 'getRoomFeatures',
        'start' => 'getStart',
        'subroom_display_names' => 'getSubroomDisplayNames',
        'timezone' => 'getTimezone',
        'title' => 'getTitle',
        'waiting_room_enabled' => 'getWaitingRoomEnabled',
        'waiting_room_welcome_note' => 'getWaitingRoomWelcomeNote'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('agenda', $data ?? [], null);
        $this->setIfExists('early_access_minutes', $data ?? [], null);
        $this->setIfExists('end', $data ?? [], null);
        $this->setIfExists('group_links', $data ?? [], null);
        $this->setIfExists('guest_links', $data ?? [], null);
        $this->setIfExists('room_features', $data ?? [], null);
        $this->setIfExists('start', $data ?? [], null);
        $this->setIfExists('subroom_display_names', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('waiting_room_enabled', $data ?? [], null);
        $this->setIfExists('waiting_room_welcome_note', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['early_access_minutes']) && ($this->container['early_access_minutes'] > 30)) {
            $invalidProperties[] = "invalid value for 'early_access_minutes', must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['early_access_minutes']) && ($this->container['early_access_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'early_access_minutes', must be bigger than or equal to 0.";
        }

        if ($this->container['end'] === null) {
            $invalidProperties[] = "'end' can't be null";
        }
        if ($this->container['room_features'] === null) {
            $invalidProperties[] = "'room_features' can't be null";
        }
        if ($this->container['start'] === null) {
            $invalidProperties[] = "'start' can't be null";
        }
        if ($this->container['timezone'] === null) {
            $invalidProperties[] = "'timezone' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['waiting_room_enabled'] === null) {
            $invalidProperties[] = "'waiting_room_enabled' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets agenda
     *
     * @return string|null
     */
    public function getAgenda()
    {
        return $this->container['agenda'];
    }

    /**
     * Sets agenda
     *
     * @param string|null $agenda The agenda of the meeting. HTML is not allowed.
     *
     * @return self
     */
    public function setAgenda($agenda)
    {
        if (is_null($agenda)) {
            array_push($this->openAPINullablesSetToNull, 'agenda');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('agenda', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['agenda'] = $agenda;

        return $this;
    }

    /**
     * Gets early_access_minutes
     *
     * @return int|null
     */
    public function getEarlyAccessMinutes()
    {
        return $this->container['early_access_minutes'];
    }

    /**
     * Sets early_access_minutes
     *
     * @param int|null $early_access_minutes The duration of the early access period to the meeting room in minutes.
     *
     * @return self
     */
    public function setEarlyAccessMinutes($early_access_minutes)
    {
        if (is_null($early_access_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'early_access_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('early_access_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($early_access_minutes) && ($early_access_minutes > 30)) {
            throw new \InvalidArgumentException('invalid value for $early_access_minutes when calling MeetingCreate., must be smaller than or equal to 30.');
        }
        if (!is_null($early_access_minutes) && ($early_access_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $early_access_minutes when calling MeetingCreate., must be bigger than or equal to 0.');
        }

        $this->container['early_access_minutes'] = $early_access_minutes;

        return $this;
    }

    /**
     * Gets end
     *
     * @return \DateTime
     */
    public function getEnd()
    {
        return $this->container['end'];
    }

    /**
     * Sets end
     *
     * @param \DateTime $end The end time of the meeting.
     *
     * @return self
     */
    public function setEnd($end)
    {
        if (is_null($end)) {
            throw new \InvalidArgumentException('non-nullable end cannot be null');
        }
        $this->container['end'] = $end;

        return $this;
    }

    /**
     * Gets group_links
     *
     * @return \Alfaview\Client\Model\GroupLinkCreate[]|null
     */
    public function getGroupLinks()
    {
        return $this->container['group_links'];
    }

    /**
     * Sets group_links
     *
     * @param \Alfaview\Client\Model\GroupLinkCreate[]|null $group_links The group links to create for the meeting. If not provided, four default group links (moderator, participant, guest, spectator) will be created. If an empty list is provided, no links will be created.
     *
     * @return self
     */
    public function setGroupLinks($group_links)
    {
        if (is_null($group_links)) {
            array_push($this->openAPINullablesSetToNull, 'group_links');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group_links', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group_links'] = $group_links;

        return $this;
    }

    /**
     * Gets guest_links
     *
     * @return \Alfaview\Client\Model\GuestLinkCreate[]|null
     */
    public function getGuestLinks()
    {
        return $this->container['guest_links'];
    }

    /**
     * Sets guest_links
     *
     * @param \Alfaview\Client\Model\GuestLinkCreate[]|null $guest_links The guest links to create for the meeting.
     *
     * @return self
     */
    public function setGuestLinks($guest_links)
    {
        if (is_null($guest_links)) {
            array_push($this->openAPINullablesSetToNull, 'guest_links');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('guest_links', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['guest_links'] = $guest_links;

        return $this;
    }

    /**
     * Gets room_features
     *
     * @return \Alfaview\Client\Model\RoomFeatures
     */
    public function getRoomFeatures()
    {
        return $this->container['room_features'];
    }

    /**
     * Sets room_features
     *
     * @param \Alfaview\Client\Model\RoomFeatures $room_features The features of the meeting room.
     *
     * @return self
     */
    public function setRoomFeatures($room_features)
    {
        if (is_null($room_features)) {
            throw new \InvalidArgumentException('non-nullable room_features cannot be null');
        }
        $this->container['room_features'] = $room_features;

        return $this;
    }

    /**
     * Gets start
     *
     * @return \DateTime
     */
    public function getStart()
    {
        return $this->container['start'];
    }

    /**
     * Sets start
     *
     * @param \DateTime $start The start time of the meeting.
     *
     * @return self
     */
    public function setStart($start)
    {
        if (is_null($start)) {
            throw new \InvalidArgumentException('non-nullable start cannot be null');
        }
        $this->container['start'] = $start;

        return $this;
    }

    /**
     * Gets subroom_display_names
     *
     * @return string[]|null
     */
    public function getSubroomDisplayNames()
    {
        return $this->container['subroom_display_names'];
    }

    /**
     * Sets subroom_display_names
     *
     * @param string[]|null $subroom_display_names The display names of the subrooms in the meeting room.
     *
     * @return self
     */
    public function setSubroomDisplayNames($subroom_display_names)
    {
        if (is_null($subroom_display_names)) {
            array_push($this->openAPINullablesSetToNull, 'subroom_display_names');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subroom_display_names', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subroom_display_names'] = $subroom_display_names;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone The time zone of the meeting.
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title The title of the meeting.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets waiting_room_enabled
     *
     * @return bool
     */
    public function getWaitingRoomEnabled()
    {
        return $this->container['waiting_room_enabled'];
    }

    /**
     * Sets waiting_room_enabled
     *
     * @param bool $waiting_room_enabled If true, participants will join the waiting room to be admitted by a moderator.
     *
     * @return self
     */
    public function setWaitingRoomEnabled($waiting_room_enabled)
    {
        if (is_null($waiting_room_enabled)) {
            throw new \InvalidArgumentException('non-nullable waiting_room_enabled cannot be null');
        }
        $this->container['waiting_room_enabled'] = $waiting_room_enabled;

        return $this;
    }

    /**
     * Gets waiting_room_welcome_note
     *
     * @return string|null
     */
    public function getWaitingRoomWelcomeNote()
    {
        return $this->container['waiting_room_welcome_note'];
    }

    /**
     * Sets waiting_room_welcome_note
     *
     * @param string|null $waiting_room_welcome_note The welcome note that is shown to the participants as they join the waiting room.
     *
     * @return self
     */
    public function setWaitingRoomWelcomeNote($waiting_room_welcome_note)
    {
        if (is_null($waiting_room_welcome_note)) {
            array_push($this->openAPINullablesSetToNull, 'waiting_room_welcome_note');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('waiting_room_welcome_note', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['waiting_room_welcome_note'] = $waiting_room_welcome_note;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


