<?php
/**
 * RoomTypeData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Alfaview\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * alfaview
 *
 * ## Format information * All time fields are returned in RFC3339 format and in UTC if not mentioned otherwise.  ## Authentication ### API Key and Credentials All API requests require an access token for authorization. Access tokens can be obtained by authenticating using any of the following endpoints: - [Authenticate via API key](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticateAPIKey) - [Authenticate via password](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticatePassword) - [Authenticate a guest (guest link)](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticateGuestLink) - [Authenticate a guest (group link)](https://apis.alfaview.com/v2/docs/openapi#/operations/AuthenticateGroupLink) The access token is returned as a base64-encoded string. It needs to be used as the value in the `Authorization` header in all subsequent API requests.  ### Token Time-To-Live (TTL) Access tokens are valid for 1 hour. After this period, tokens will be expired and a new token must be obtained.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alfaview\Client\Model;

use \ArrayAccess;
use \Alfaview\Client\ObjectSerializer;

/**
 * RoomTypeData Class Doc Comment
 *
 * @category Class
 * @package  Alfaview\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RoomTypeData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RoomTypeData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'max_active_participants' => 'int',
        'max_spectator_only_participants' => 'int',
        'max_sub_rooms' => 'int',
        'name' => 'string',
        'total' => 'int',
        'used' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'max_active_participants' => 'int32',
        'max_spectator_only_participants' => 'int32',
        'max_sub_rooms' => 'int32',
        'name' => null,
        'total' => 'int64',
        'used' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'max_active_participants' => false,
        'max_spectator_only_participants' => false,
        'max_sub_rooms' => false,
        'name' => false,
        'total' => false,
        'used' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'max_active_participants' => 'maxActiveParticipants',
        'max_spectator_only_participants' => 'maxSpectatorOnlyParticipants',
        'max_sub_rooms' => 'maxSubRooms',
        'name' => 'name',
        'total' => 'total',
        'used' => 'used'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'max_active_participants' => 'setMaxActiveParticipants',
        'max_spectator_only_participants' => 'setMaxSpectatorOnlyParticipants',
        'max_sub_rooms' => 'setMaxSubRooms',
        'name' => 'setName',
        'total' => 'setTotal',
        'used' => 'setUsed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'max_active_participants' => 'getMaxActiveParticipants',
        'max_spectator_only_participants' => 'getMaxSpectatorOnlyParticipants',
        'max_sub_rooms' => 'getMaxSubRooms',
        'name' => 'getName',
        'total' => 'getTotal',
        'used' => 'getUsed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('max_active_participants', $data ?? [], null);
        $this->setIfExists('max_spectator_only_participants', $data ?? [], null);
        $this->setIfExists('max_sub_rooms', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('used', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['max_active_participants'] === null) {
            $invalidProperties[] = "'max_active_participants' can't be null";
        }
        if (($this->container['max_active_participants'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_active_participants', must be bigger than or equal to 0.";
        }

        if ($this->container['max_spectator_only_participants'] === null) {
            $invalidProperties[] = "'max_spectator_only_participants' can't be null";
        }
        if (($this->container['max_spectator_only_participants'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_spectator_only_participants', must be bigger than or equal to 0.";
        }

        if ($this->container['max_sub_rooms'] === null) {
            $invalidProperties[] = "'max_sub_rooms' can't be null";
        }
        if (($this->container['max_sub_rooms'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_sub_rooms', must be bigger than or equal to 0.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['total'] === null) {
            $invalidProperties[] = "'total' can't be null";
        }
        if (($this->container['total'] < 0)) {
            $invalidProperties[] = "invalid value for 'total', must be bigger than or equal to 0.";
        }

        if ($this->container['used'] === null) {
            $invalidProperties[] = "'used' can't be null";
        }
        if (($this->container['used'] < 0)) {
            $invalidProperties[] = "invalid value for 'used', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets max_active_participants
     *
     * @return int
     */
    public function getMaxActiveParticipants()
    {
        return $this->container['max_active_participants'];
    }

    /**
     * Sets max_active_participants
     *
     * @param int $max_active_participants The maximum number of active participants allowed in this room type.
     *
     * @return self
     */
    public function setMaxActiveParticipants($max_active_participants)
    {
        if (is_null($max_active_participants)) {
            throw new \InvalidArgumentException('non-nullable max_active_participants cannot be null');
        }

        if (($max_active_participants < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_active_participants when calling RoomTypeData., must be bigger than or equal to 0.');
        }

        $this->container['max_active_participants'] = $max_active_participants;

        return $this;
    }

    /**
     * Gets max_spectator_only_participants
     *
     * @return int
     */
    public function getMaxSpectatorOnlyParticipants()
    {
        return $this->container['max_spectator_only_participants'];
    }

    /**
     * Sets max_spectator_only_participants
     *
     * @param int $max_spectator_only_participants The maximum number of spectator-only participants in this room type.
     *
     * @return self
     */
    public function setMaxSpectatorOnlyParticipants($max_spectator_only_participants)
    {
        if (is_null($max_spectator_only_participants)) {
            throw new \InvalidArgumentException('non-nullable max_spectator_only_participants cannot be null');
        }

        if (($max_spectator_only_participants < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_spectator_only_participants when calling RoomTypeData., must be bigger than or equal to 0.');
        }

        $this->container['max_spectator_only_participants'] = $max_spectator_only_participants;

        return $this;
    }

    /**
     * Gets max_sub_rooms
     *
     * @return int
     */
    public function getMaxSubRooms()
    {
        return $this->container['max_sub_rooms'];
    }

    /**
     * Sets max_sub_rooms
     *
     * @param int $max_sub_rooms The maximum number of subrooms in this room type.
     *
     * @return self
     */
    public function setMaxSubRooms($max_sub_rooms)
    {
        if (is_null($max_sub_rooms)) {
            throw new \InvalidArgumentException('non-nullable max_sub_rooms cannot be null');
        }

        if (($max_sub_rooms < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_sub_rooms when calling RoomTypeData., must be bigger than or equal to 0.');
        }

        $this->container['max_sub_rooms'] = $max_sub_rooms;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the room type.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets total
     *
     * @return int
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param int $total The total quota of this room type.
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }

        if (($total < 0)) {
            throw new \InvalidArgumentException('invalid value for $total when calling RoomTypeData., must be bigger than or equal to 0.');
        }

        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets used
     *
     * @return int
     */
    public function getUsed()
    {
        return $this->container['used'];
    }

    /**
     * Sets used
     *
     * @param int $used The number of existing rooms using this room type.
     *
     * @return self
     */
    public function setUsed($used)
    {
        if (is_null($used)) {
            throw new \InvalidArgumentException('non-nullable used cannot be null');
        }

        if (($used < 0)) {
            throw new \InvalidArgumentException('invalid value for $used when calling RoomTypeData., must be bigger than or equal to 0.');
        }

        $this->container['used'] = $used;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


