<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roomService/roomService.proto

namespace Alfatraining\Grpc\Room;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roomService.CreateJoinLinkReply</code>
 */
class CreateJoinLinkReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     */
    private $replyInfo = null;
    /**
     * Generated from protobuf field <code>string joinLink = 14;</code>
     */
    private $joinLink = '';

    public function __construct() {
        \GPBMetadata\RoomService\RoomService::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     * @return \Alfatraining\Grpc\Common\ReplyInfo
     */
    public function getReplyInfo()
    {
        return $this->replyInfo;
    }

    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     * @param \Alfatraining\Grpc\Common\ReplyInfo $var
     * @return $this
     */
    public function setReplyInfo($var)
    {
        GPBUtil::checkMessage($var, \Alfatraining\Grpc\Common\ReplyInfo::class);
        $this->replyInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string joinLink = 14;</code>
     * @return string
     */
    public function getJoinLink()
    {
        return $this->joinLink;
    }

    /**
     * Generated from protobuf field <code>string joinLink = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setJoinLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->joinLink = $var;

        return $this;
    }

}

