<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roomService/roomService.proto

namespace Alfatraining\Grpc\Room;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roomService.RoomsUpdateReply</code>
 */
class RoomsUpdateReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     */
    private $replyInfo = null;
    /**
     * key is the room ID
     *
     * Generated from protobuf field <code>map<string, .common.ReplyInfo> updateReplies = 2;</code>
     */
    private $updateReplies;

    public function __construct() {
        \GPBMetadata\RoomService\RoomService::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     * @return \Alfatraining\Grpc\Common\ReplyInfo
     */
    public function getReplyInfo()
    {
        return $this->replyInfo;
    }

    /**
     * Generated from protobuf field <code>.common.ReplyInfo replyInfo = 1;</code>
     * @param \Alfatraining\Grpc\Common\ReplyInfo $var
     * @return $this
     */
    public function setReplyInfo($var)
    {
        GPBUtil::checkMessage($var, \Alfatraining\Grpc\Common\ReplyInfo::class);
        $this->replyInfo = $var;

        return $this;
    }

    /**
     * key is the room ID
     *
     * Generated from protobuf field <code>map<string, .common.ReplyInfo> updateReplies = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getUpdateReplies()
    {
        return $this->updateReplies;
    }

    /**
     * key is the room ID
     *
     * Generated from protobuf field <code>map<string, .common.ReplyInfo> updateReplies = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setUpdateReplies($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Alfatraining\Grpc\Common\ReplyInfo::class);
        $this->updateReplies = $arr;

        return $this;
    }

}

