<?php
/**
 * AuthenticationListGuestAccountsRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * authentication/authenticationService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

/**
 * AuthenticationListGuestAccountsRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ListGuestAccountsRequest is used to list guest accounts for a specific room.
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthenticationListGuestAccountsRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuthenticationListGuestAccountsRequest"
     */
    public function testAuthenticationListGuestAccountsRequest()
    {
    }

    /**
     * Test attribute "access_info"
     */
    public function testPropertyAccessInfo()
    {
    }

    /**
     * Test attribute "room_id"
     */
    public function testPropertyRoomId()
    {
    }

    /**
     * Test attribute "guest_id_list"
     */
    public function testPropertyGuestIdList()
    {
    }
}
