<?php
/**
 * AuthenticationAuthenticationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * authService/authenticationService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

use PHPUnit\Framework\TestCase;


/**
 * AuthenticationAuthenticationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description * AuthenticationRequest contains everything needed to authenticate a user on our platform.
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthenticationAuthenticationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AuthenticationAuthenticationRequest"
     */
    public function testAuthenticationAuthenticationRequest()
    {
    }

    /**
     * Test attribute "access_info"
     */
    public function testPropertyAccessInfo()
    {
    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "username_password_credentials"
     */
    public function testPropertyUsernamePasswordCredentials()
    {
    }

    /**
     * Test attribute "authorization_code_credentials"
     */
    public function testPropertyAuthorizationCodeCredentials()
    {
    }

    /**
     * Test attribute "refresh_token_credentials"
     */
    public function testPropertyRefreshTokenCredentials()
    {
    }

    /**
     * Test attribute "ldap_credentials"
     */
    public function testPropertyLdapCredentials()
    {
    }

    /**
     * Test attribute "guest_access_credentials"
     */
    public function testPropertyGuestAccessCredentials()
    {
    }

    /**
     * Test attribute "activation_token_credentials"
     */
    public function testPropertyActivationTokenCredentials()
    {
    }

    /**
     * Test attribute "company_switch_credentials"
     */
    public function testPropertyCompanySwitchCredentials()
    {
    }

    /**
     * Test attribute "permissions"
     */
    public function testPropertyPermissions()
    {
    }

    /**
     * Test attribute "account_status"
     */
    public function testPropertyAccountStatus()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }
}
