<?php
/**
 * AuthenticationAuthenticationCreateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * authService/authenticationService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

use PHPUnit\Framework\TestCase;


/**
 * AuthenticationAuthenticationCreateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AuthenticationCreateRequest carries all the required information to create authentication methods for a user. This is only used if the user ID is not known and should be picked by the authentication service, otherwise use the AuthenticationUpdateRequest.
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthenticationAuthenticationCreateRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AuthenticationAuthenticationCreateRequest"
     */
    public function testAuthenticationAuthenticationCreateRequest()
    {
    }

    /**
     * Test attribute "access_info"
     */
    public function testPropertyAccessInfo()
    {
    }

    /**
     * Test attribute "authentication_request"
     */
    public function testPropertyAuthenticationRequest()
    {
    }
}
