<?php
/**
 * BusinessLogicServiceInviteUsersReplyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * businessLogicService/businessLogicService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

use PHPUnit\Framework\TestCase;


/**
 * BusinessLogicServiceInviteUsersReplyTest Class Doc Comment
 *
 * @category    Class
 * @description * InviteUsersReply contains the common reply information of the response to the InviteUsersRequest.
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BusinessLogicServiceInviteUsersReplyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BusinessLogicServiceInviteUsersReply"
     */
    public function testBusinessLogicServiceInviteUsersReply()
    {
    }

    /**
     * Test attribute "reply_info"
     */
    public function testPropertyReplyInfo()
    {
    }

    /**
     * Test attribute "tracking_info"
     */
    public function testPropertyTrackingInfo()
    {
    }
}
