<?php
/**
 * CompanyServiceBillingInformationUpdateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * companyService/companyService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

/**
 * CompanyServiceBillingInformationUpdateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description * BillingInformationUpdateRequest can be used to update the billing information of a company.
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyServiceBillingInformationUpdateRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompanyServiceBillingInformationUpdateRequest"
     */
    public function testCompanyServiceBillingInformationUpdateRequest()
    {
    }

    /**
     * Test attribute "access_info"
     */
    public function testPropertyAccessInfo()
    {
    }

    /**
     * Test attribute "company_id"
     */
    public function testPropertyCompanyId()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "plan_id"
     */
    public function testPropertyPlanId()
    {
    }
}
