<?php
/**
 * CompanyServiceCompanySearchReplyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * companyService/companyService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

/**
 * CompanyServiceCompanySearchReplyTest Class Doc Comment
 *
 * @category    Class
 * @description CompanyServiceCompanySearchReply
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyServiceCompanySearchReplyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompanyServiceCompanySearchReply"
     */
    public function testCompanyServiceCompanySearchReply()
    {
    }

    /**
     * Test attribute "reply_info"
     */
    public function testPropertyReplyInfo()
    {
    }

    /**
     * Test attribute "continue"
     */
    public function testPropertyContinue()
    {
    }

    /**
     * Test attribute "total_results"
     */
    public function testPropertyTotalResults()
    {
    }

    /**
     * Test attribute "accurate_total"
     */
    public function testPropertyAccurateTotal()
    {
    }

    /**
     * Test attribute "companies"
     */
    public function testPropertyCompanies()
    {
    }

    /**
     * Test attribute "ordered_company_i_ds"
     */
    public function testPropertyOrderedCompanyIDs()
    {
    }
}
