<?php
/**
 * GuestServiceV2UpdateGuestLinkReplyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * guestServiceV2/guestService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

use PHPUnit\Framework\TestCase;

/**
 * GuestServiceV2UpdateGuestLinkReplyTest Class Doc Comment
 *
 * @category    Class
 * @description GuestServiceV2UpdateGuestLinkReply
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GuestServiceV2UpdateGuestLinkReplyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GuestServiceV2UpdateGuestLinkReply"
     */
    public function testGuestServiceV2UpdateGuestLinkReply()
    {
    }

    /**
     * Test attribute "reply_info"
     */
    public function testPropertyReplyInfo()
    {
    }

    /**
     * Test attribute "tracking_info"
     */
    public function testPropertyTrackingInfo()
    {
    }
}
