<?php
/**
 * RoomQuotasTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Alfaview\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * alfaview
 *
 * ## General format information * All time fields are returned in RFC3339 format and in UTC if not mentioned otherwise.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Alfaview\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RoomQuotasTest Class Doc Comment
 *
 * @category    Class
 * @description RoomQuotas
 * @package     Alfaview\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RoomQuotasTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RoomQuotas"
     */
    public function testRoomQuotas()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "active_participants"
     */
    public function testPropertyActiveParticipants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spectator_only_participants"
     */
    public function testPropertySpectatorOnlyParticipants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subrooms"
     */
    public function testPropertySubrooms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
