<?php
/**
 * UserUserListReplyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * userService/userService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfaview;

/**
 * UserUserListReplyTest Class Doc Comment
 *
 * @category    Class
 * @description UserUserListReply
 * @package     Alfaview
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserUserListReplyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserUserListReply"
     */
    public function testUserUserListReply()
    {
    }

    /**
     * Test attribute "reply_info"
     */
    public function testPropertyReplyInfo()
    {
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
    }

    /**
     * Test attribute "user_id_list"
     */
    public function testPropertyUserIdList()
    {
    }
}
