<?php
/**
 * GuestsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Alfaview\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * alfaview
 *
 * ## General format information * All time fields are returned in RFC3339 format and in UTC if not mentioned otherwise.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Alfaview\Client\Test\Api;

use Alfaview\Client\Alfaview;
use \Alfaview\Client\Configuration;
use \Alfaview\Client\ApiException;
use Alfaview\Client\Model\APICredentials;
use Alfaview\Client\Model\GroupLinkCreate;
use Alfaview\Client\Model\GuestLinkCreate;
use Alfaview\Client\Model\CreateGroupLinksRequestBody;
use Alfaview\Client\Model\CreateGuestLinksRequestBody;
use Alfaview\Client\Model\RoomCreate;
use \Alfaview\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GuestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alfaview\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GuestsApiTest extends TestCase
{
    protected Alfaview $alfaview;

    protected APICredentials $credentials;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->alfaview = new Alfaview();
        $this->alfaview->setHost(getenv('API_HOST'));

        $this->credentials = new APICredentials();
        $this->credentials->setClientId(getenv('API_CLIENT_ID'));
        $this->credentials->setKey(getenv('API_CODE'));
        $this->credentials->setCompanyId(getenv('API_COMPANY_ID'));
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
        $accessToken = $this->alfaview->authenticationApi->authenticateAPIKey($this->credentials);
        $response = $this->alfaview->roomsApi->listRooms($accessToken->getAccessToken());

        foreach ($response->getData() as $room) {
            if (strpos($room->getDisplayName(), 'created by php-sdk') !== false) {
                $this->alfaview->roomsApi->deleteRoom($room->getId(), $accessToken->getAccessToken());
            }
        }
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createGroupLink
     *
     * Create group links.
     *
     */
    public function testCreateGroupLink()
    {
        $accessToken = $this->alfaview->authenticationApi->authenticateAPIKey($this->credentials);

        $roomCreate = new RoomCreate();
        $roomCreate->setDisplayName('room created by php-sdk V2');
        $roomCreate->setType(RoomCreate::TYPE_ROOM);
        $roomCreate->setWaitingRoomEnabled(false);

        $room = $this->alfaview->roomsApi->createRoom($roomCreate, $accessToken->getAccessToken());
        $roomId = $room->getId();
        $this->assertNotEmpty($roomId);

        $permissionGroups = $this->alfaview->roomsApi->listPermissionGroups($accessToken->getAccessToken());
        $participantPermissionGroupId = null;
        foreach ($permissionGroups as $permissionGroup) {
            if ($permissionGroup->getName() === 'Participant') {
                $participantPermissionGroupId = $permissionGroup->getId();
            }
        }

        $groupLink = new GroupLinkCreate();
        $groupLink->setDescription('PHP SDK Group Link');
        $groupLink->setDialInAllowed(false);
        $groupLink->setPermissionGroupId($participantPermissionGroupId);
        $groupLink->setValidUntil(new \DateTime('next week today'));

        $groupLinksRequest = new CreateGroupLinksRequestBody();
        $groupLinksRequest->setCreate([$groupLink]);

        $groupLinkResponse = $this->alfaview->guestsApi->createGroupLink($roomId, $groupLinksRequest, $accessToken->getAccessToken());

        $this->assertNotEmpty($groupLinkResponse[0]->getId());
    }

    /**
     * Test case for createGuestLinks
     *
     * Create guest links.
     *
     */
    public function testCreateGuestLinks()
    {
        $accessToken = $this->alfaview->authenticationApi->authenticateAPIKey($this->credentials);

        $roomCreate = new RoomCreate();
        $roomCreate->setDisplayName('room created by php-sdk V2');
        $roomCreate->setType(RoomCreate::TYPE_ROOM);
        $roomCreate->setWaitingRoomEnabled(false);

        $room = $this->alfaview->roomsApi->createRoom($roomCreate, $accessToken->getAccessToken());
        $roomId = $room->getId();
        $this->assertNotEmpty($roomId);

        $permissionGroups = $this->alfaview->roomsApi->listPermissionGroups($accessToken->getAccessToken());
        $spectatorPermissionGroupId = null;
        foreach ($permissionGroups as $permissionGroup) {
            if ($permissionGroup->getName() === 'Spectator') {
                $spectatorPermissionGroupId = $permissionGroup->getId();
            }
        }

        $guestLink = new GuestLinkCreate();
        $guestLink->setDisplayName('Spectator Guest Link');
        $guestLink->setDialInAllowed(false);
        $guestLink->setEmailAddress('test@example.com');
        $guestLink->setSendEmail(false);
        $guestLink->setLocale('en-EN');
        $guestLink->setPermissionGroupId($spectatorPermissionGroupId);
        $guestLink->setValidUntil(new \DateTime('next week today'));

        $guestLinksRequest = new CreateGuestLinksRequestBody();
        $guestLinksRequest->setCreate([$guestLink]);

        $guestLinkResponse = $this->alfaview->guestsApi->createGuestLinks($roomId, $guestLinksRequest, $accessToken->getAccessToken());

        $this->assertNotEmpty($guestLinkResponse[0]->getId());
    }

    /**
     * Test case for deleteGroupLink
     *
     * Delete group link.
     *
     */
    public function testDeleteGroupLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteGuestLink
     *
     * Delete guest link.
     *
     */
    public function testDeleteGuestLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getGroupLink
     *
     * Get group link.
     *
     */
    public function testGetGroupLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getGuestLink
     *
     * Get guest link.
     *
     */
    public function testGetGuestLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listGroupLinks
     *
     * List group links.
     *
     */
    public function testListGroupLinks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listGroupLinksForRoom
     *
     * List group links for room.
     *
     */
    public function testListGroupLinksForRoom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listGuestLinks
     *
     * List guest links.
     *
     */
    public function testListGuestLinks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listGuestLinksForRoom
     *
     * List guest links for a room.
     *
     */
    public function testListGuestLinksForRoom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGroupLink
     *
     * Update group link.
     *
     */
    public function testUpdateGroupLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGuestLink
     *
     * Update guest link.
     *
     */
    public function testUpdateGuestLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
