<?php
/**
 * UserServiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * user/userService.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Alfaview;

use \Alfaview\Configuration;
use \Alfaview\ApiException;
use \Alfaview\ObjectSerializer;

/**
 * UserServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alfaview
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserServiceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for userCreate
     *
     * .
     *
     */
    public function testUserCreate()
    {
    }

    /**
     * Test case for userDestroy
     *
     * .
     *
     */
    public function testUserDestroy()
    {
    }

    /**
     * Test case for userGetLocale
     *
     * .
     *
     */
    public function testUserGetLocale()
    {
    }

    /**
     * Test case for userList
     *
     * .
     *
     */
    public function testUserList()
    {
    }

    /**
     * Test case for userProfileUpdate
     *
     * .
     *
     */
    public function testUserProfileUpdate()
    {
    }

    /**
     * Test case for userUpdate
     *
     * .
     *
     */
    public function testUserUpdate()
    {
    }
}
